### ISSUE TITLE
file header lacks dash

### ISSUE THREAD

**Issue by steckerhalter** [jleechpe/outorg-export#1]
the first line of the elisp currently is:

``` cl
;;; outorg-export.el -- Automated exporting through org
```

http://www.gnu.org/software/emacs/manual/html_node/elisp/Library-Headers.html states that it should be three dashes and not two:

``` cl
;;; outorg-export.el --- Automated exporting through org
```

see https://github.com/quelpa/quelpa/issues/66 for more info

Thanks!

**Comment by jleechpe** [comment]
Thank you.

Not sure how that slipped through, I don't remember manually writing the header.

Fixed in cb0dc625a20481f852097c2f22fc09242b0c6474
